dog_ceo_block_admin_config.config_menu:
  path: '/admin/config/dog-breed/slug'
  defaults:
    _form: '\Drupal\dog_ceo_block_admin_config\Form\DogSlugBlockConfigForm'
    _title: 'Dog Slug Config'
  requirements:
    _permission: 'administer site configuration'
